// Generated by Supabase CLI - do not edit manually
// Run: pnpm db:types to regenerate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      churches: {
        Row: {
          attendance_bracket: string | null
          ccli_license_number: string | null
          created_at: string | null
          id: string
          name: string
          planning_center_token: string | null
          settings: Json | null
          stripe_customer_id: string | null
          subscription_status: string | null
        }
        Insert: {
          attendance_bracket?: string | null
          ccli_license_number?: string | null
          created_at?: string | null
          id?: string
          name: string
          planning_center_token?: string | null
          settings?: Json | null
          stripe_customer_id?: string | null
          subscription_status?: string | null
        }
        Update: {
          attendance_bracket?: string | null
          ccli_license_number?: string | null
          created_at?: string | null
          id?: string
          name?: string
          planning_center_token?: string | null
          settings?: Json | null
          stripe_customer_id?: string | null
          subscription_status?: string | null
        }
        Relationships: []
      }
      events: {
        Row: {
          church_id: string
          created_at: string | null
          id: string
          items: Json
          scheduled_at: string | null
          status: string | null
          title: string
        }
        Insert: {
          church_id: string
          created_at?: string | null
          id?: string
          items?: Json
          scheduled_at?: string | null
          status?: string | null
          title: string
        }
        Update: {
          church_id?: string
          created_at?: string | null
          id?: string
          items?: Json
          scheduled_at?: string | null
          status?: string | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "events_church_id_fkey"
            columns: ["church_id"]
            isOneToOne: false
            referencedRelation: "churches"
            referencedColumns: ["id"]
          },
        ]
      }
      media: {
        Row: {
          church_id: string
          created_at: string | null
          dominant_color: string | null
          id: string
          metadata: Json | null
          source: string | null
          source_id: string | null
          storage_path: string
          tags: string[] | null
          thumbnail_path: string | null
          type: string
        }
        Insert: {
          church_id: string
          created_at?: string | null
          dominant_color?: string | null
          id?: string
          metadata?: Json | null
          source?: string | null
          source_id?: string | null
          storage_path: string
          tags?: string[] | null
          thumbnail_path?: string | null
          type: string
        }
        Update: {
          church_id?: string
          created_at?: string | null
          dominant_color?: string | null
          id?: string
          metadata?: Json | null
          source?: string | null
          source_id?: string | null
          storage_path?: string
          tags?: string[] | null
          thumbnail_path?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "media_church_id_fkey"
            columns: ["church_id"]
            isOneToOne: false
            referencedRelation: "churches"
            referencedColumns: ["id"]
          },
        ]
      }
      song_usage: {
        Row: {
          ccli_song_id: string | null
          church_id: string
          displayed_at: string | null
          event_id: string | null
          id: string
          song_id: string
        }
        Insert: {
          ccli_song_id?: string | null
          church_id: string
          displayed_at?: string | null
          event_id?: string | null
          id?: string
          song_id: string
        }
        Update: {
          ccli_song_id?: string | null
          church_id?: string
          displayed_at?: string | null
          event_id?: string | null
          id?: string
          song_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "song_usage_church_id_fkey"
            columns: ["church_id"]
            isOneToOne: false
            referencedRelation: "churches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "song_usage_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "song_usage_song_id_fkey"
            columns: ["song_id"]
            isOneToOne: false
            referencedRelation: "songs"
            referencedColumns: ["id"]
          },
        ]
      }
      songs: {
        Row: {
          author: string | null
          ccli_song_id: string | null
          church_id: string
          content: Json
          created_at: string | null
          default_arrangement: Json | null
          default_background_id: string | null
          id: string
          key: string | null
          last_used_at: string | null
          tags: string[] | null
          tempo: number | null
          title: string
          transition_type: string | null
        }
        Insert: {
          author?: string | null
          ccli_song_id?: string | null
          church_id: string
          content?: Json
          created_at?: string | null
          default_arrangement?: Json | null
          default_background_id?: string | null
          id?: string
          key?: string | null
          last_used_at?: string | null
          tags?: string[] | null
          tempo?: number | null
          title: string
          transition_type?: string | null
        }
        Update: {
          author?: string | null
          ccli_song_id?: string | null
          church_id?: string
          content?: Json
          created_at?: string | null
          default_arrangement?: Json | null
          default_background_id?: string | null
          id?: string
          key?: string | null
          last_used_at?: string | null
          tags?: string[] | null
          tempo?: number | null
          title?: string
          transition_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "songs_church_id_fkey"
            columns: ["church_id"]
            isOneToOne: false
            referencedRelation: "churches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "songs_default_background_fkey"
            columns: ["default_background_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          church_id: string
          created_at: string | null
          email: string
          id: string
          name: string
          role: string
        }
        Insert: {
          church_id: string
          created_at?: string | null
          email: string
          id: string
          name: string
          role?: string
        }
        Update: {
          church_id?: string
          created_at?: string | null
          email?: string
          id?: string
          name?: string
          role?: string
        }
        Relationships: [
          {
            foreignKeyName: "users_church_id_fkey"
            columns: ["church_id"]
            isOneToOne: false
            referencedRelation: "churches"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_church_id: { Args: Record<string, never>; Returns: string }
      get_user_role: { Args: Record<string, never>; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
