// This file is auto-generated by Supabase CLI
// Run: pnpm db:types to regenerate

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      churches: {
        Row: {
          id: string;
          name: string;
          attendance_bracket: string | null;
          stripe_customer_id: string | null;
          subscription_status: string | null;
          ccli_license_number: string | null;
          planning_center_token: string | null;
          settings: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          attendance_bracket?: string | null;
          stripe_customer_id?: string | null;
          subscription_status?: string | null;
          ccli_license_number?: string | null;
          planning_center_token?: string | null;
          settings?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          attendance_bracket?: string | null;
          stripe_customer_id?: string | null;
          subscription_status?: string | null;
          ccli_license_number?: string | null;
          planning_center_token?: string | null;
          settings?: Json | null;
          created_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          church_id: string;
          role: string;
          name: string;
          email: string;
          created_at: string;
        };
        Insert: {
          id: string;
          church_id: string;
          role: string;
          name: string;
          email: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          role?: string;
          name?: string;
          email?: string;
          created_at?: string;
        };
      };
      songs: {
        Row: {
          id: string;
          church_id: string;
          title: string;
          author: string | null;
          ccli_song_id: string | null;
          key: string | null;
          tempo: number | null;
          content: Json;
          default_arrangement: Json | null;
          default_background_id: string | null;
          transition_type: string | null;
          tags: string[] | null;
          last_used_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          title: string;
          author?: string | null;
          ccli_song_id?: string | null;
          key?: string | null;
          tempo?: number | null;
          content: Json;
          default_arrangement?: Json | null;
          default_background_id?: string | null;
          transition_type?: string | null;
          tags?: string[] | null;
          last_used_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          title?: string;
          author?: string | null;
          ccli_song_id?: string | null;
          key?: string | null;
          tempo?: number | null;
          content?: Json;
          default_arrangement?: Json | null;
          default_background_id?: string | null;
          transition_type?: string | null;
          tags?: string[] | null;
          last_used_at?: string | null;
          created_at?: string;
        };
      };
      media: {
        Row: {
          id: string;
          church_id: string;
          type: string;
          storage_path: string;
          thumbnail_path: string | null;
          source: string;
          source_id: string | null;
          dominant_color: string | null;
          tags: string[] | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          type: string;
          storage_path: string;
          thumbnail_path?: string | null;
          source?: string;
          source_id?: string | null;
          dominant_color?: string | null;
          tags?: string[] | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          type?: string;
          storage_path?: string;
          thumbnail_path?: string | null;
          source?: string;
          source_id?: string | null;
          dominant_color?: string | null;
          tags?: string[] | null;
          metadata?: Json | null;
          created_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          church_id: string;
          title: string;
          scheduled_at: string | null;
          items: Json;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          title: string;
          scheduled_at?: string | null;
          items?: Json;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          title?: string;
          scheduled_at?: string | null;
          items?: Json;
          status?: string;
          created_at?: string;
        };
      };
      song_usage: {
        Row: {
          id: string;
          church_id: string;
          song_id: string;
          event_id: string | null;
          ccli_song_id: string | null;
          displayed_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          song_id: string;
          event_id?: string | null;
          ccli_song_id?: string | null;
          displayed_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          song_id?: string;
          event_id?: string | null;
          ccli_song_id?: string | null;
          displayed_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
